### ISSUE TITLE
Lazy load fails on video invoked from a playlist

### ISSUE THREAD

**Issue by dizzib** [JustOff/youtube-lazy-load#1]
For example, any video invoked from playlist https://www.youtube.com/watch?v=C6G2ADJ61GA&list=PL7Wwl5TzliiHSlk6Ol7xEGiUxa69fVsk- will play immediately.

v1.0.1
Palemoon 27.3.0 (64 bit)
Arch Linux

**Comment by JustOff** [comment]
Each player activates only once, next video from playlist and autoplay starts without extra confirmations. This is by design.

**Comment by dizzib** [comment]
Ok thanks! Just in case anyone else wants this I've fixed it here: https://github.com/dizzib/youtube-lazy-load/commit/4aa7a110ff98a2f664bc2b68e8956a107745a017
