### ISSUE TITLE
No YouTube

### ISSUE THREAD

**Issue by beep54** [JustOff/youtube-lazy-load#2]
Not sure, but this seems to actually disable YouTube in my Pale Moon forcing me to use Chrome. Note: I hate autoload of any sort (looking at you BBC!) and so was hopeful about this addon.

**Comment by JustOff** [comment]
I myself use YouTube (HTML5 player) everyday with this add-on. Probably you have some conflict with other extensions or browser settings. Try to start from clean profile to find the conflict.

**Comment by JustOff** [comment]
Closing this for now, please update if you find the culprit.
