### ISSUE TITLE
Add-on Broken by another update- 2020 edition

### ISSUE THREAD

**Issue by Faedelity** [JustOff/youtube-lazy-load#4]
As of the last month or two, there have been several YouTube format updates, and one of them has broken the function of this addon. I am hoping it is still being maintained, because I very much appreciated not having every YouTube video I open in a tab for a serial watching session going bonkers at once.

**Comment by JustOff** [comment]
Duplicate of #3

**Comment by rpodric** [comment]
Is it a duplicate of a thread concerning updates made in 2017? I'm not so sure.

In the here and now, is there a way around it? I noticed it upon using the latest YouTube format with PaleMoon 28.8.2.1.

**Comment by JustOff** [comment]
> Is it a duplicate of a thread concerning updates made in 2017? I'm not so sure.

Yes, it is. See also [discontinuing older version of YouTube on desktop](https://support.google.com/youtube/thread/27596769).

> In the here and now, is there a way around it?

As soon as a solution is found, I will definitely share it.
