### ISSUE TITLE
Compatiblity issue with uBO Legacy after YouTube update

### ISSUE THREAD

**Issue by LL25255252** [JustOff/youtube-lazy-load#7]
Before about March 22 I used both this addon and uBO Legacy with no issues on Pale Moon.
On about March 22 youtube changed something and videos can't play -  "an error occurred. Please try again late".
After I disabled uBO Legacy on youtube.com the issue is gone (also Youtube Lazy Load works OK again)
So can you please make these 2 addons work together again (without the need to disable uBO on youtube) ?

Pale Moon 28.8.4 (32 bit)
uBO Legacy 1.16.4.20
Youtube Lazy Load 1.0.4
Win 7 x64
Thanks in advance.

**Comment by JustOff** [comment]
Your issue has nothing to do with Youtube Lazy Load, see also https://forum.palemoon.org/viewtopic.php?f=3&t=24032.

**Comment by LL25255252** [comment]
I tried to update my uBO filters as recommended in the thread you mentioned but still getting  "an error occurred. Please try again late"
Just to make sure I understand your reply : Do you @JustOff manage to watch youtube videos with YLL without ads ?
If so, do you use uBO Legacy ?

Pale Moon 28.8.4 (32 bit)
uBO Legacy 1.16.4.20
Youtube Lazy Load 1.0.4
Win 7 x64

**Comment by JustOff** [comment]
Yes, I use uBO Legacy in Pale Moon and don't have ads on YouTube. And no, unfortunately I can't help you figure out why it works differently for you, sorry.
